name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Website Staging Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'botblock',
              repo: 'static-site',
              workflow_id: 'deployment-staging.yml',
              ref: 'staging',
            });

      - name: Trigger Website Production Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'botblock',
              repo: 'static-site',
              workflow_id: 'deployment-production.yml',
              ref: 'production',
            });

      - name: Trigger API Staging Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'botblock',
              repo: 'api-worker',
              workflow_id: 'deployment-staging.yml',
              ref: 'staging',
            });

      - name: Trigger API Production Deployment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.USER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'botblock',
              repo: 'api-worker',
              workflow_id: 'deployment-production.yml',
              ref: 'production',
            });
